export const NavLinksList = {
	LINK_EN: [
		{ name: 'Achievements', url: '#achievements' },
		{ name: 'Sponsors', url: '#sponsors' },
		{ name: 'Team Members', url: '#team' },
		{ name: 'FAQ', url: '#faq' },
		{ name: 'About Us', url: '/about' },
		// { name: 'Blog', url: '/blog' },
	],
	LINK_ZH: [
		{ name: '功能', url: '#achievements' },
		{ name: '定价', url: '#sponsors' },
		{ name: '评价', url: '#team' },
		{ name: '常见问题', url: '#faq' },
		{ name: '关于我们', url: '/about' },
		{ name: '博客', url: '/blog' },
	],
	LINK_ES: [
		{ name: 'Logros', url: '#achievements' },
		{ name: 'Patrocinadores', url: '#sponsors' },
		{ name: 'Miembros del equipo', url: '#team' },
		{ name: 'FAQ', url: '#faq' },
		{ name: 'Sobre nosotros', url: '/about' },
		// { name: 'Blog', url: '/blog' },
	],
	LINK_RU: [
		{ name: 'Функция', url: '#achievements' },
		{ name: 'Цены', url: '#sponsors' },
		{ name: 'Отзыв', url: '#team' },
		{ name: 'ЧаВО', url: '#faq' },
		{ name: 'О нас', url: '/about' },
		{ name: 'Блог', url: '/blog' },
	],
	LINK_JA: [
		{ name: '特徴', url: '#achievements' },
		{ name: '価格', url: '#sponsors' },
		{ name: 'お客様の声', url: '#team' },
		{ name: 'よくある質問', url: '#faq' },
		{ name: '私たちについて', url: '/about' },
		{ name: 'ブログ', url: '/blog' },
	],
	LINK_AR: [
		{ name: 'ميزة', url: '#achievements' },
		{ name: 'التسعير', url: '#sponsors' },
		{ name: 'شهادة', url: '#team' },
		{ name: 'الأسئلة الشائعة', url: '#faq' },
		{ name: 'معلومات عنا', url: '/about' },
		{ name: 'مدونة', url: '/blog' },
	],
	LINK_FR: [
		{ name: 'Fonctionnalités', url: '#achievements' },
		{ name: 'Tarification', url: '#sponsors' },
		{ name: 'Témoignages', url: '#team' },
		{ name: 'FAQ', url: '#faq' },
		{ name: 'À propos de nous', url: '/about' },
		{ name: 'Blog', url: '/blog' },
	],
};
